version: '3.8'

services:
  # 2. 레디스
  redis:
    image: redis:latest
    container_name: suratgan-redis
    ports:
      - "6379:6379"
    networks:
      - delivery-network
    restart: always

  # 3. 데이터베이스 (기존 pgrouting 설정 유지)
  db:
    image: pgrouting/pgrouting:15-3.3-3.4.1
    container_name: pgrouting
    environment:
      - POSTGRES_DB=sura
      - POSTGRES_USER=sura
      - POSTGRES_PASSWORD=sura
      - TZ=Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - delivery_db_data:/var/lib/postgresql/data
    networks:
      - delivery-network
    restart: always

networks:
  delivery-network:
    driver: bridge

volumes:
  delivery_db_data: